import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import React from 'react';
import { useRouter } from 'next/navigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'LangChain exercise',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-amber-50 p-10 md:p-20 ${inter.className}`}>
        <div className="w-full p-10 grid place-items-center border-amber-300 border-2">
          {children}
        </div>
      </body>
    </html>
  );
}
